# Import necessary libraries
import openai
import streamlit as st
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import os

openai.api_key = os.environ.get("OPENAI_API_KEY")

def detect_gpt3(prompt):
    generated_text = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=2048,
        n=1,
        stop=None,
        temperature=0.5,
    ).choices[0].text

    prompt_vect = text_to_vector(prompt)
    generated_text_vect = text_to_vector(generated_text)

    return cosine_similarity([prompt_vect],[generated_text_vect])[0][0]

st.title("GPT-3 Text Detection App")

text = st.text_area("Enter text to check if generated by GPT-3:")

if st.button("Check"):
    similarity = detect_gpt3(text)
    if similarity > 0.9:
        st.success("The text is generated by GPT-3")
    else:
        st.error("The text is not generated by GPT-3")
